# Generated by Django 3.1.6 on 2021-02-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
